language: ruby
rvm:
- 2.3.0
env:
- RACK_ENV=test
addons:
  postgresql: "9.4"
cache:
  directories:
    - vendor/bundle
    - node_modules
    - travis_phantomjs
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- "phantomjs --version"
- "export PATH=$PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH"
- "phantomjs --version"
- "if [ $(phantomjs --version) != '2.1.1' ]; then rm -rf $PWD/travis_phantomjs; mkdir -p $PWD/travis_phantomjs; fi"
- "if [ $(phantomjs --version) != '2.1.1' ]; then wget https://assets.membergetmember.co/software/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2; fi"
- "if [ $(phantomjs --version) != '2.1.1' ]; then tar -xvf $PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs; fi"
- "phantomjs --version"
before_script:
- psql -c 'create database berg_test;' -U postgres
- cp ./config/application.travisci.yml ./config/application.yml
- nvm install 4.4.2
- nvm use 4.4.2
- npm install -g npm
- npm install
script:
- bundle exec rake assets:precompile
- bundle exec rake db:migrate
- bundle exec rake spec
notifications:
  email: false
  slack:
    on_success: change
    on_failure: change
    rooms:
      - icelab:6dXO9CHlWw9h4xhLSlGr9Hhv
