language: ruby
rvm:
- 2.3.0
env:
- RACK_ENV=test
addons:
  postgresql: "9.4"
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- psql -c 'create database berg_test;' -U postgres
- cp ./config/application.travisci.yml ./config/application.yml
- nvm install 4.4.2
- nvm use 4.4.2
- npm install -g npm
- npm install
script:
- bundle exec rake assets:precompile
- bundle exec rake db:migrate
- bundle exec rake spec
notifications:
  email: false
